config/routes.rb
DeviseTodoApp::Application.routes.draw do

  devise_for :users, path: 'accounts'

  devise_scope :user do
    get "/accounts/sign_in" => "devise/sessions#new", as: "signin"   # no need for this...but i did this because in y previous todo app...i had tests that used the signin_path often to go to the signin page...so here i have created a named route : signin_path ....its route is same as new_session_path which devise creates by default....so in tests u can use either of them..see http://stackoverflow.com/questions/4503550/route-alias-in-rails  and http://guides.rubyonrails.org/routing.html#overriding-the-named-helpers   for more
  end

  resources :users do
    resources :lists do
      resources :tasks
    end

  end

  root to: 'pages#home'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  attr_accessible :description, :name
  validates :name, presence: true
  validates :user, presence: true        # can also write it as validates :user_id, presence: true
  default_scope order: 'lists.created_at DESC'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  attr_accessible :description,:completed
  validates :description, presence: true
  validates :list, presence: true
  scope :completed ,where(completed:true)
  scope :incomplete, where(completed: false)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email,:nick_name, :password, :password_confirmation, :remember_me
  validates :nick_name, presence: true    # the other fields already validated by devise
  has_many :lists , dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include CustomDeviseHelper1 #I named it with a 1 , because it doesn't seem to save if I save as custom_devise_helper.rb ....faced similar problem in another project....have to find out the problem
  include SessionsHelper1   #This only includes the helpers in the controller
  helper SessionsHelper1 #  To access these helpers in the views , you must use it....this is a rspec-rails 2.10.1 issue
  layout :layout_by_resource #For changing layout for specfic controller actions of devise
  before_filter :set_no_cache
  private
  def set_no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!
  before_filter  {|c| c.correct_user params[:user_id] }   # Use block form ....This is the way to send parameters to method used in
  def create
    @list = current_user.lists.build(params[:list])
    respond_to do |format|
      format.js
    end
  end

  def show
    @list = List.find_by_id(params[:id])
    @task =@list.tasks.build
  end

  def destroy
    @list = List.find_by_id(params[:id])
    @destroyed_list = @list.destroy
    respond_to do |format|
      format.js
    end
  end

  def update
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    if user_signed_in?
      @lists = current_user.lists.all    # Don't do current_user.lists
      @new_list = current_user.lists.build
    end
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :authenticate_user!
  before_filter  {|c| c.correct_user params[:user_id] }   # Use block form ....This is the way to send parameters to method used in
  before_filter :find_list
  def create
    @task = @list.tasks.build(params[:task])
    respond_to do |format|
      format.js
    end
  end


  def update
    @task =@list.tasks.find(params[:id])
    @task.update_attributes(params[:task])
    respond_to do |format|
      format.js
    end
  end

  def destroy
   @destroyed_task = @list.tasks.destroy(params[:id])
   @destroyed_task = @destroyed_task.first    # we do this bcos , above command returns an rray of destroyed task objects
   respond_to do |format|
     format.js
   end
  end

  private

  def find_list
    redirect_to root_path unless @list= current_user.lists.find_by_id(params[:list_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  before_filter :correct_user, except: [:index,:destroy]
  before_filter :admin_user ,only:[:destroy]

  def edit
  end

  def index
    @users = User.all
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to root_path, notice: 'Profile updated'
    else
      render 'edit'
    end
  end

  def destroy
    if User.find(params[:id]).destroy
      redirect_to users_path, notice: 'User deleted'
    end
  end


  private

  def correct_user
    @user = User.find_by_id(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_devise_helper1.rb
module CustomDeviseHelper1
  def devise_sessions_controller?
    is_a?(Devise::SessionsController)
  end

  def devise_registrations_controller?
    is_a?(Devise::RegistrationsController)
  end

  #For changing layout for specfic controller actions of devise
  def layout_by_resource
    if (devise_sessions_controller? || devise_registrations_controller?) && resource_name == :user
      "sessions"
    else
      "application"
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper


    def resource_name
      :user
    end

    def resource
      @resource ||= User.new
    end

    def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end

end

app/helpers/sessions_helper1.rb
module SessionsHelper1


  def current_user?(user)
    current_user==user
  end

  def correct_user(user_id)
    @user = User.find(user_id)
    redirect_to root_path unless current_user?(@user)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoodle - <%=yield :title%></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header class='navbar navbar-fixed-top navbar-inverse'>
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">Todoodle</a>
          <nav>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                  <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
                  <li><%= link_to 'Edit profile', edit_user_path(current_user) %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% else %>
                  <%= render 'devise/sessions/new_inline' %>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

<div class='container main_container'>
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key==:notice ? 'success' : 'error' %>">
        <a class="close" data-dismiss="alert" href="#">&times;</a><%= value %>
      </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoodle - <%=yield :title%></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class='navbar navbar-fixed-top navbar-inverse'>
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">Todoodle</a>
      <nav>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
              <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
              <li><%= link_to 'Edit profile', edit_user_path(current_user) %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

<div class='container main_container'>
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key==:notice ? 'success' : 'error' %>">
        <a class="close" data-dismiss="alert" href="#">&times;</a><%= value %>
      </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/lists/_index.html.erb
<h3 class='main_header'>My TODO Lists</h3>
<div class="lists" id="lists">
  <ul class="lists">

   <%= render @lists if @lists.present?%>
    <div id='lists_empty' class='centre hero-unit'>You have no lists ! Create a list now !</div>  <!--We show this if there are no lists and hide it if a list  is created-->
  </ul>
</div>

app/views/lists/_list.html.erb
<div id="list_<%= list.id %>">
  <li><%= link_to list.name, user_list_path(current_user.id, list.id), class: 'item_names' %>
  </li>&emsp;
  <%= link_to '(remove)',user_list_path(current_user,list),method: :delete,remote: true %>
</div>

app/views/lists/_new.html.erb
<%= simple_form_for [current_user,new_list], class:'form-horizontal',remote: true  do |f|%>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/lists/create.js.erb
<% if @list.save %>
$('ul.lists').append('<%= j render @list %>');
<% @list = List.new(); %>
$('#new_list').html('<%= j render("lists/new",new_list:@list) %>');
<% else %>
$('#new_list').html('<%= j render("lists/new",new_list:@list) %>');
<% end %>

app/views/lists/destroy.js.erb
<%if @destroyed_list %>
 $('div#list_<%=@destroyed_list.id %>').remove();
<% else %>
// Add an error message
<% end %>

app/views/lists/show.html.erb
<%= content_for :title, @list.name %>
<div class='parent_div'><h2 class='main_header'><%= @list.name %> </h2>

  <div class='list_desc'>--<i><%= @list.description %></i></div>
</div>

Unfinished Tasks
<div class='tasks'id='incomplete_tasks'>
  <div class='empty_message'><div class='center hero-unit' id='tasks_empty'>My little grasshopper..You have no tasks left to do !</div></div>
  <% @list.tasks.incomplete.each do |task| %>
      <%= render task %>
  <% end %>
</div>
Finished Tasks
<div class='tasks'id='completed_tasks'>
  <% @list.tasks.completed.each do |task| %>
      <%= render task %>
  <% end %>
</div>


<%= render 'tasks/new' %>

app/views/pages/_home_not_signed_in.html.erb
<%= content_for(:title,'Welcome') %>
<div class="center hero-unit">
  <h1>Welcome to Todoodly</h1>
  <h2>
    This is the home page for
    my sample ToDo List App
  </h2>
  <%=link_to 'Sign up now !',new_user_registration_path,class: "btn btn-large btn-primary" %>
</div>

app/views/pages/_home_signed_in.html.erb
<%= content_for(:title,'Home') %>

<div id='user_nick_name'>Hi <%=current_user.nick_name %> !</div>
<%= render 'lists/index' %>
<%= render 'lists/new',new_list:@new_list %>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <%= render 'home_signed_in' %>
<% else %>
    <%= render 'home_not_signed_in' %>
<% end %>

app/views/pages/index.html.erb
This is the index , It means you are not signed in !

app/views/tasks/_new.html.erb
<%= simple_form_for([current_user,@list,@task],class:'form-horizontal',remote:true) do |f| %>
    <%= f.input :description, required: true %>
    <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<%= form_for [current_user, @list, task], remote: true do |f| %>
    <%= f.label 'completed_'+task.object_id.to_s, class: 'checkbox' do %>
        <%= f.check_box :completed ,id:'task_completed_'+task.object_id.to_s%>   <!--have overridden default id because label works only if there is a unique id in each page-->
        <%= task.description %>
    <% end %>
    <%= link_to "remove",user_list_task_path(current_user, @list, task),method: :delete,remote: true %>
    <%= f.submit "Update" %>        <!--We hide this button in jquery-->
<% end %>

app/views/tasks/create.js.erb
<% if @task.save %>
 $('#incomplete_tasks').append('<%= j render @task %>');
<% @task = @list.tasks.build %>
$('#new_task').html('<%= j render "tasks/new"   %>')
 //show error message
<% end %>

app/views/tasks/destroy.js.erb
<% if @destroyed_task %>
  $('#edit_task_<%=@destroyed_task.id %>').remove();
<%else %>
//show error message
<% end %>

app/views/tasks/update.js.erb
<% if @task.completed? %>
$('#edit_task_<%= @task.id %>').appendTo('#completed_tasks');
<% else %>
$('#edit_task_<%=@task.id %>').appendTo('#incomplete_tasks');
<% end %>

app/views/users/_user.html.erb
<li>
  <%= user.nick_name %>&emsp;
  <% if current_user.admin? && !current_user?(user)%>
      <%= link_to 'remove', user_path(user), method: :delete, data: {confirm: "You're sure ?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<%= content_for :title,'Edit profile' %>
<h2>Edit profile</h2>
<%= simple_form_for @user, class: 'form-horizontal' do |f| %>
    <%= f.input :nick_name ,required: true%>
    <%= f.submit 'Update profile' %>
<% end %>

app/views/users/index.html.erb
<% provide(:title,'All users') %>
<h2>All users</h2>
<ul class='users'>
  <%= render @users %>
</ul>